In [1]:
import pandas as pd
import sys
sys.path.append('..')
from pipeline.preprocessors.revisedMissing import RevisedMissingValueHandler
from pipeline.preprocessors.numerical import Scaler

In [3]:
df = pd.read_csv('../../data/diabetes.csv')

In [6]:
impossibles = ['Glucose', 'BloodPressure', 'SkinThickness', 'BMI']
missing_handler = RevisedMissingValueHandler(
    drop_cols=['Insulin'],
    impute_cols=impossibles,
    zero_cols=impossibles
)

df_clean = missing_handler.fit_transform(df)

In [7]:
scaler = Scaler(scale_cols=['Glucose', 'BloodPressure', 'SkinThickness',
                             'BMI', 'Pregnancies', 'DiabetesPedigreeFunction', 'Age'])
df_scaled = scaler.fit_transform(df_clean)
df_scaled.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,BMI,DiabetesPedigreeFunction,Age,Outcome
0,0.635626,0.857470,-0.029161,6.501609e-01,0.163790,0.450630,1.423376,1
1,-0.848175,-1.202734,-0.515471,-1.706081e-02,-0.855381,-0.375786,-0.194857,0
2,1.229146,2.002028,-0.677574,3.950746e-16,-1.335847,0.585372,-0.109687,1
3,-0.848175,-1.071927,-0.515471,-6.842825e-01,-0.636987,-0.926730,-1.046559,0
4,-1.144936,0.497752,-2.622814,6.501609e-01,1.546951,5.424097,-0.024517,1

In [8]:
df_scaled.describe().round(2)

,Pregnancies,Glucose,BloodPressure,SkinThickness,BMI,DiabetesPedigreeFunction,Age,Outcome
count,733.00,733.00,733.00,733.00,733.00,733.00,733.00,733.00
mean,-0.00,-0.00,-0.00,0.00,0.00,0.00,-0.00,0.34
std,1.00,1.00,1.00,1.00,1.00,1.00,1.00,0.48
min,-1.14,-2.54,-3.92,-2.46,-2.08,-1.19,-1.05,0.00
25%,-0.85,-0.71,-0.68,-0.57,-0.72,-0.69,-0.79,0.00
50%,-0.25,-0.16,-0.03,0.00,-0.01,-0.29,-0.37,0.00
75%,0.64,0.63,0.62,0.43,0.60,0.46,0.66,1.00
max,3.90,2.53,4.02,7.77,5.04,5.82,4.06,1.00

In [9]:
df_scaled['Outcome'].value_counts()

Outcome
0    481
1    252
Name: count, dtype: int64